### ISSUE TITLE
BCNM Loot Display

### ISSUE THREAD

**Issue by TeoTwawki** [LegionDark/Website#1]
**Feature Name**: BCNM loot info displays _somewhere/anywhere_
**Feature Information**: findable/listing of BCNM loot drops would be very handy
**Feature Page/Url**: n/a (wherever makes sense to you)
**Additional Information**: 
_Reminder per our IRC discussion_
BCNM loot tool or BCNM drop info added to item info  or drop info tool(s).
Separate BCNM tool probably best way to approach it.

**Comment by atom0s** [comment]
Thanks, will probably add something similar to the current tools. A list of all the BCNMs on the server on one page. While having full details of the BCNM on another page when selected. Should be simple enough to add in the near future once I have the newest version of the site up and running live.

**Comment by atom0s** [comment]
This tool is now added to the main site. :)
