### ISSUE TITLE
Bazaar Search Buy/Sell

### ISSUE THREAD

**Issue by R3P0FFXI** [LegionDark/Website#10]
Feature Name: Bazaar Search Buy/Sell
Feature Information: Search all Bazaars in game via the website, unsure if Buy/Sell would be possible
Feature Page/URL: Located Behind Player login

**Comment by Baucant** [comment]
Could this also be attached to item pages to show Who is currently bazaaring the item we are looking at.

**Comment by atom0s** [comment]
Rather than searching bazaars I think  what Baucant recommended seems like a better method of doing this. Having bazaars listed on item result pages makes more sense. Just look up an item to find it in a bazaar etc. I don't see a point in having searches specific to bazaars otherwise.

**Comment by atom0s** [comment]
Alright, item pages will now display (at the bottom) a list of players bazaaring that item. (If any.)
