### ISSUE TITLE
Item Stats not showing on Mouse Over

### ISSUE THREAD

**Issue by Zeldha** [LegionDark/Website#12]
**Feature Name**: Item Stats Show on mouse-over
**Feature Information**: Item Stats Show on mouse-over 
**Feature Page/Url**: after searching NM/mobs, and click the what the NM drop.
**Additional Information**: On old website i remember if we put mouse icon (mouse-over) in top of the item, it will show the stats.

Sample on SS after searching Crypt Ghost and take a look the drop.
![mouse_over](https://cloud.githubusercontent.com/assets/16524259/13221394/2903bb50-d9b6-11e5-86f0-8893dc356171.jpg)

**Comment by atom0s** [comment]
This feature is moved to the icons now. Hover your mouse over the item icons and it will show the tooltip. The links to the items are now internal links to the sites item tool. Because of that, the AH tooltips will not work on those links anymore.

**Comment by Zeldha** [comment]
@atom0s  ,
Checking this with other 2 LS member, thought it was my browser problem (firefox). But 2 of them have same result as me, the icon doesnt show it stats.
Clicking the icon will bring us to FFXIAH. It probably better to make the AH link to open in new tab.

**Comment by atom0s** [comment]
Can you give me a link to a page that has this problem?

**Comment by Zeldha** [comment]
@atom0s 
**Step:**
Monster tool > Tiamat > click name to show the drop item > the drop item list icon not showing stats on mouse hover.
Did try on another NM too. Ex: Tablilla ect.

**Comment by atom0s** [comment]
I can't reproduce this. It is working fine on my end. Are you blocking javascript or similar in any manner? This makes use of external scripts from other sites so those need to be enabled.

**Comment by Zeldha** [comment]
@atom0s 
I cant find what blocking it.
But, if i take a look my AH history or any other players, i can see the item info if I mouse hover on icon.
I see the link info for icon is connected to FFXI AH, and its the same with mobs drop list.
But in mobs drop list, doesn't show the stats or info on item icon mouse hover.

**Comment by atom0s** [comment]
Try now should be fixed.

**Comment by Zeldha** [comment]
Fixed! Nice, thank you.
