### ISSUE TITLE
leisilonu +1     no info

### ISSUE THREAD

**Issue by Zeldha** [LegionDark/Website#14]
**Bug Date & Time**: Peb 23, 2016
**Bug Name**: No Item Info
**Bug Page/Url**: http://legiondark.com/db/items/20634/leisilonu_+1
**Bug Information**: page error
**Steps To Reproduce The Bug**: trying to find info about leisilonu +1, click the item and error page.
**Additional Information**:

**Comment by atom0s** [comment]
Appears this is due to having the item name in the url. Thanks for the report, looking into this.

**Comment by atom0s** [comment]
This should now be fixed.
