### ISSUE TITLE
Sorting

### ISSUE THREAD

**Issue by Baucant** [LegionDark/Website#15]
**Feature Name**: Sort function
**Feature Information**:The ability to sort by either zone, mob name or drop rate
**Feature Page/Url**:http://legiondark.com/db/items

**Comment by atom0s** [comment]
(Nvm my previous response, I misread.)

**Comment by atom0s** [comment]
This is now added.

**Comment by Baucant** [comment]
any chance you can add the little up down arrows so people know they can sort it.....
