### ISSUE TITLE
The Emissary (Windurst) mission

### ISSUE THREAD

**Issue by Akuma9** [LegionDark/Website#18]
When I try to complete "The Emissary (Windurst)" the game freezes and can not continue.
My character's name is Akuma, race is Elvaan, and job is BLM. the nation of origin is Bastok, I began from San d'Oria then I went to Windurst. I hope this information helps.

**Comment by atom0s** [comment]
Great job reading the read me.....

**Comment by Akuma9** [comment]
I am sorry atom0s, I am new to this and I just read the "README.md, but I did not see anything that mentioned this mission. I was told that this was a known issue. I am pretty sure if you tell me what I need to do that I can rectify my error. 

```
On Thursday, February 25, 2016 10:57 PM, atom0s <notifications@github.com> wrote:
```

 Great job reading the read me.....—

**Comment by TeoTwawki** [comment]
@Akuma9 he's not telling you its mentioned in the readme...If you actually read the page you are on here you aren't even in the right place. 

LegionDark/**Website**/issues/18

Is your mission problem a website bug? I don't think so. You want

https://github.com/LegionDark/Issues

For game server support. And in both trackers threes a template required, spelled out in the read me..

**Comment by Akuma9** [comment]
I made a new request. 

Sent from Outlook Mobile

On Thu, Feb 25, 2016 at 8:38 PM -0800, "TeoTwawki" notifications@github.com wrote:

@Akuma9 he's not telling you its mentioned in the readme...If you actually read the page you are on here you aren't even in the right place. 

LegionDark/Website/issues/18

Is your mission problem a website bug? I don't think so. You want

https://github.com/LegionDark/Issues

For game server support. And in both trackers threes a template required, spells out in the read me..
