### ISSUE TITLE
Clean Look Design

### ISSUE THREAD

**Issue by Zeldha** [LegionDark/Website#2]
**Feature Name**: Clean/Simple Look Design Interface.
**Feature Information**: 
**Feature Page/Url**: beta.legiondark
**Additional Information**: Hi, I am a Graphic Designer. Personaly, I love the clean look on the current website, not to many object for eye to focus on. And is very user friendly. The color scheme also really nice.
Is it possible to re arrange the layout same as current website (side bar).
The loading animation also too big, and feel old.
I can help u with the banner/tittle design if u need it.

**Comment by atom0s** [comment]
I have updated the loading animation and the site now has a banner on the newest live version. Please check it out. As for the sidebar. For the time being this is setup to only be on the right side. I may add the ability to swap them in a later update though.

**Comment by atom0s** [comment]
Closing this as most of what was asked is implemented. If you would like, please remake a separate ticket for the sidebar request.
