### ISSUE TITLE
Front Page News Posts

### ISSUE THREAD

**Issue by neuromancerxi** [LegionDark/Website#25]
Feature Name: Front Page News Posts
Feature Information: Add Date/Time/Posted By
Feature Page/Url: Front Page (www.legiondark.com)
Additional Information: Would be nice if the links back to the forum led to a Forum that can be viewed without having to be logged into the forums.

**Comment by atom0s** [comment]
I can look into adding time posted, but I was against readding who posted what to avoid people ignoring news posted by specific people. 

As for the links going back to a required login that is a forum permission issue I'll adjust.

**Comment by atom0s** [comment]
This is now added to the bottom of each news post.
