### ISSUE TITLE
item browser issue 

### ISSUE THREAD

**Issue by benfolka** [LegionDark/Website#26]
**Bug Date & Time**: 15.10 gmt+2
**Bug Name**: item browser drop list issue
**Bug Page/Url**: http://legiondark.com/db/items/28015/xaddi_gauntlets
**Bug Information**: xaddi gaunlets list drop from unknown and there is a clickable link for it
**Steps To Reproduce The Bug**:
**Additional Information**: xaddi gaunlets were tiamat drop before

**Comment by benfolka** [comment]
also checked this monster 
http://legiondark.com/db/monsters/17056187/Morta
@pos 280 1 396 5
it may be out of map bounds or invalid monster 
not sure

**Comment by benfolka** [comment]
http://legiondark.com/db/items/269/shadow_lord_statue
same issue

**Comment by benfolka** [comment]
http://legiondark.com/db/monsters/17056187/Morta
this monster may be out of map bounds

**Comment by atom0s** [comment]
The website pulls this information from the database directly. If drops appear incorrect than this is an issue to report on the main issue tracker. You can report these issues here:
https://github.com/LegionDark/Issues
