### ISSUE TITLE
Monster Tool - Some mob names are not correct.

### ISSUE THREAD

**Issue by Rohelius** [LegionDark/Website#27]
**Bug Date & Time**: 3/19/16
**Bug Name**: "Monster Tool naming Error" ?
**Bug Page/Url**:  http://legiondark.com/db/monsters/17056187/Morta
**Bug Information**:  It seems Jormy was called Morta with drop table and all~
**Steps To Reproduce The Bug**: look up Any Xaddi gear that is dropped from Jormy and Morta would pop up in page, which is incorrect.
**Additional Information**:  IT seems several Wyrms had their gear either removed or shuffled (not sure if purposefully or by mistake.

Seems loot tables have been fixed in Website as of 3/21/16. Posting this on the Website bug tracker on Teo's Request :)

**Comment by atom0s** [comment]
@TeoTwawki This is an issue with the database, the website just reports what's in there. Nothing I can do about this since this requires fixes to the dababase itself, not the site.
