### ISSUE TITLE
Item Tool, error on clicking item after search

### ISSUE THREAD

**Issue by JanIvarOyulvstad** [LegionDark/Website#28]
Error description:
1) Look up item (OK)
2) Item is found and this is clicked (OK)
3) Item Crafting is opened (OK, shows recipe)
4) Clicking on the material items show error (ERROR)

Here is an example:
1) Haruspex Cuffs
2) Can open
3) Recipe shos (Clothcraft 103)
4) Clicking on Silk Cloth gives error

Shows the link:
http://www.legiondark.com/db/item/829/

Correct would be:
http://www.legiondark.com/db/items/2340/square_of_imperial_silk_cloth

**Comment by atom0s** [comment]
Fixed, next time please follow the template when making a ticket.
