### ISSUE TITLE
Crystal War mission Bug

### ISSUE THREAD

**Issue by Shokii** [LegionDark/Website#30]
For the past month, I've had an issue with the Crystal War. Here is  all the quest that I have completed  the Crystal War mission; *Steamed Rims, *Gifts of Griffon, *Claws of the Griffon, *Boy and the beast. Every time I return to Sandy in the future I talk to the void officer but he doesn't do anything. He talks about this dance but nothing else. I wiki it says I need to complete just one mission to earn entrance into the ​void watch but I've done 4. Please if there is anything I can do please contact me.

**Comment by atom0s** [comment]
Invalid template, wrong tracker. Closing.

**Comment by Shokii** [comment]
Sorry, but what does that mean?

**Comment by Shokii** [comment]
I can't log in anymore on FFXI, did my account get removed?

**Comment by Shokii** [comment]
I will correct it. I found the web site that was very detailed. Thanks ^_^
