### ISSUE TITLE
Crystal War mission Bug

### ISSUE THREAD

**Issue by Shokii** [LegionDark/Website#31]
Date & Time: 4/27/2016

FFXI Client Version (use /ver): 30160329_1

Character Name: Shokii

Nation: The Kingdom of San d’Oria

Job(level)/Sub Job(level): NIN(99)/War(66)

NPC or Monster or item Name: Voidwatch Officer

Zone name & Coordinates (use @where): Souther San d’Oria (F-9)
ffxiah.com link (for items issues only): N/A

Multi-boxing? (multiple clients on same connection): Yes, Grievan.

Steps To Reproduce / any other info: 
![shokii_2016 04 27_044855](https://cloud.githubusercontent.com/assets/18668270/14871227/565f6ad8-0cae-11e6-87bb-f1765c680aa4.png)

For the past month, I've had an issue with the Crystal War missions. Here is all the quest that I have completed the Crystal War mission; *Steamed Rims, *Gifts of Griffon, *Claws of the Griffon, *Boy and the beast. Every time I return to Sandy in the future I talk to the void officer but he doesn't give me anything. He talks about this dance but nothing else. I wiki it says I need to complete just one mission to earn entrance into the void watch but I've done 4. Please if there is anything I can do please contact me

**Comment by atom0s** [comment]
And again this is not the correct tracker for server issues.
