### ISSUE TITLE
Mob tool handling of "respawn time"

### ISSUE THREAD

**Issue by TeoTwawki** [LegionDark/Website#32]
**Feature Name**: info display adjustment
**Feature Information**: respawn time & spawn type
**Feature Page/Url**: http://legiondark.com/db/monsters
**Additional Information**: ~~when the database respawn time is zero and the spawn type is scripted, I think it would be less confusing to the players to not display the respawn time from the database. I'm aware we can't fetch the repop time form the script, so I'm saying lets not state one at all when we have those 2 conditions.~~ **Lets just put scripted for both fields, when mob is scripted.** I'm kinda tired and my talky bits aren't working very well.

**Comment by atom0s** [comment]
This is added and will be in the next push to the website.
