### ISSUE TITLE
BLU tool not showing correct results

### ISSUE THREAD

**Issue by Midgardsormr** [LegionDark/Website#33]
The Blue Mage tool says that Rail Cannon is available from various Chariots (which I have never seen in-game). The spell is, in fact, learnable from the Sub-zero Gears in Abyssea-Uleguerand. 

Not sure if I should be submitting this here, so I will also submit in the server bug list.

**Comment by atom0s** [comment]
The spell information on what can be learned is pulled from the database. The Chariots may just be invalid mobs at the time and not properly implemented but they are still marked as using this ability so the tool still lists them. 

Some mobs have the chance to learn the BLU spell in their script which the site does not pull data from. The Sub-Zero Gears are one of them that do this. So they are not listed on the site. This is not really something I can fix unless someone else adds the spell to the database.

I'd recommend making a ticket on the main issue tracker for the server and request that this be added to the database so it shows up on the BLU tool list. If you know of other spells that are the same you can request those as well.
