### ISSUE TITLE
Current online players (mobile version)

### ISSUE THREAD

**Issue by Gigas0813** [LegionDark/Website#34]
**Feature Name**:  Current online players (mobile version)
**Feature Information**:  On the mobile version of the homepage It would be nice to see who is currently online like it is currently on the desktop homepage.  This could just be displayed differently on my phone (samsung s5 w/ google chrome), but if not it would be convenient ... or if there is a way to see a desktop version on mobile like some other websites do.  
**Feature Page/Url**: home page
**Additional Information**:  This is mostly just a convenience since sometimes I decide whether I want to decide to turn on my computer to play or not if people are on.  Dunno if other people would suggest this.  If not then just ignore this suggestion lol.

**Comment by atom0s** [comment]
This is something I plan to add as a separate page for mobile viewers to use. As is, the site looks like crap when compressed to small screen sizes with the sidebar displaying.

**Comment by Gigas0813** [comment]
makes sense.  good plan!

**Comment by atom0s** [comment]
Forgot to mark this as completed a while ago. This can be found here:
http://legiondark.com/whosonline/

From the main website you can find it as the top option under 'Database Tools'.
