### ISSUE TITLE
Display expected client version (ECV) on index page.

### ISSUE THREAD

**Issue by TeoTwawki** [LegionDark/Website#36]
**Feature Name**: Expected Client Version 
**Feature Information**: Display ECV (expected client version) on index page.
**Feature Page/Url**: http://legiondark.com/
**Additional Information**:
Example:
`Expected Client Version: 30160329_0`

Placing it with server status or above online player roster would be ideal.
In the repository root `version.info` will contain the following string:

```
#Expected Client version (wrong version cannot log in)
CLIENT_VER: 30160329_0
```

So we can grab it from there and it'll automatically update when the files are updated via pull.

**Comment by TeoTwawki** [comment]
In teh repository root `version.info` will contain the following string:
```#Expected Client version (wrong version cannot log in)
CLIENT_VER: 30160427_0```

**Comment by atom0s** [comment]
Added.
