### ISSUE TITLE
NPC Wahraga has Item Relic Staff in list of items instead of Wind Fan

### ISSUE THREAD

**Issue by EpicTaru** [LegionDark/Website#41]
Date & Time:

FFXI Client Version (use /ver):
30170304_1

Server's Expected Client Version matches, yes/no? (use $ecv):
Yes

Character Name:
EpicTaru

Nation:
San d'Oria

Job(level)/Sub Job(level):
THF99/DNC49

NPC or Monster or item Name:
Wahraga

Zone name:
Aht Urhgan Whitegate

Coordinates (use $where):
X:- 76  Y: -6  Z: 137 (192)

ffxiah.com link (for items issues only):
http://www.ffxiah.com/item/18326/relic-staff
http://www.ffxiah.com/item/18236/wind-fan

Multi-boxing? (multiple clients on same connection):
No

Steps To Reproduce / any other info:
1. /check Wahraga (at Alchemists' Guild).
2. Observe there is no Wind Fan in the list of items buyable from the NPC.
3. Observe there is a Relic Staff in the list of items buyable from the NPC.

FFXIAH was used to identify the Item IDs for both of the above items.  Appears that the 2 and the 3 in the Item ID were transposed in place of each other, causing the Relic Staff to be a buyable item in place of a Wind Fan.

I did confirm that you can buy a Relic Staff from this NPC.  I still have the Relic Staff in my inventory.

Thanks for all you do!

EpicTaru

**Comment by atom0s** [comment]
This is the wrong tracker to be posting bug reports in-game for. This is for the website.
