### ISSUE TITLE
Password Reset Request for Forums, am returning player

### ISSUE THREAD

**Issue by YehoshuaEmpyrean** [LegionDark/Website#42]
**Bug Date & Time**:      7/29/2017 7:30PM EST
**Bug Name**:    I'm the bug. I can not remember my password, sorry I'm dumb
**Bug Page/Url**: [http://legiondark.com/forums/ucp.php?mode=login](url)
**Bug Information**: CANNOT log into [http://legiondark.com/forums/ucp.php?mode=login](url) but CAN [http://legiondark.com/account/login](url)
**Steps To Reproduce The Bug**:
I am the bug. I forgot my login information for the forums. 
**Additional Information**:
Hey I'm josh, I believe I have two accounts for legiondark.com forums joshksales@gmail.com and yehoshuaempyrean@gmail.com I know one of the usernames was either Yehoshua or YehoshuaEmpyrean. Please forgive me :)

**Comment by atom0s** [comment]
Is this still an issue? Generally, password resets for the forums were not posted here. I can help if this is still an issue though.

**Comment by YehoshuaEmpyrean** [comment]
This is resolved sorry for not closing. It's been eventful
