### ISSUE TITLE
Website tools down

### ISSUE THREAD

**Issue by ghost** [LegionDark/Website#43]
**Bug Date & Time**: Last few days
**Bug Name**: Website tools down
**Bug Page/Url**: http://www.legiondark.com/db/bcnms, http://www.legiondark.com/db/characters, http://www.legiondark.com/db/items, http://www.legiondark.com/db/items, http://www.legiondark.com/db/monsters, http://www.legiondark.com/db/bluespells
**Bug Information**: All searches come back "Sorry, no [blank] were found."
**Steps To Reproduce The Bug**: Use tools search feature.
**Additional Information**:

**Comment by atom0s** [comment]
Everything should be good to go and working again. More info here:
http://legiondark.com/forums/viewtopic.php?f=21&t=2171
