### ISSUE TITLE
Link to the working/nonworking BCNM/KSNM wiki article

### ISSUE THREAD

**Issue by EpicTaru** [LegionDark/Website#46]
Feature Name: Link to the working/nonworking BCNM/KSNM wiki article
Feature Information: A weblink to the LD wiki article for the BCNMs and KSNMs that are working/not working (http://wiki.legiondark.com/BCNM/KSNM_Status)
Feature Page/Url: Server Tools > BCNM Tool
Additional Information: Have a link to the wiki article displayed at the top of the BCNM Tool page. This would connect the two information sources to each other and aid in informing players of which BCNM/KSNMs work/don't work before they go searching thru the BCNM Tool.

**Comment by atom0s** [comment]
Done.
