### ISSUE TITLE
Apkallu Fletchings selling too high to vendors

### ISSUE THREAD

**Issue by Bruce101** [LegionDark/Website#49]
**Bug Date & Time**: January 22 2018 approximately 6PM MST 
**Bug Name**: Item has too high a selling price
**Bug Page/Url**:http://ffxiclopedia.wikia.com/wiki/Apkallu_Fletchings
**Bug Information**: the wiki says they should sell for 3-4 gil each, !shop 1 was paying 1052 each.
**Steps To Reproduce The Bug**: I sold 1 fletching, checked my gil amount and sold 1 more to test difference 
**Additional Information**: I wasn't sure if the price listed in my menu was for the whole stack or a single, so I sold a single, the price didn't alter, so I wrote down my gil amount, sold another one and determined that the fletchings are selling for too much. It was 1052 gil, supposed to be only 3-4. I was trying to get rid of unwanted junk by selling to !shop 1.

**Comment by atom0s** [comment]
This is not a website issue. Please report it to the server tracker instead.
